### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by darkelfzdy** [InkTimeRecord/TTime#161]
请提供下述完整信息以便快速定位问题 / Please provide the following information to quickly locate the problem

- 系统环境 / System Environment：Windows 10，通过v2rayN上网（绕过大陆）

- TTime版本号 / TTime Version：0.8.2

- 问题描述 / Description of the issue：
 部分翻译源无法翻译

我通过Alt+E翻译：Appalachia’s Gentrification - Clash of Locals & Outsiders 🇺🇸
deepl和bing翻译有结果
火山翻译反馈：Error: Cannot read properties of undefined (reading '0')
小牛翻译反馈：{"message":"Request failed with status code 400","name":"AxiosError","stack":"AxiosError: Request failed with status code 400\n    at settle (D:\\tools\\TTime\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:1896:12)\n    at IncomingMessage.handleStreamEnd (D:\\tools\\TTime\\resources\\app.asar\\node_modules\\axios\\dist\\node\\axios.cjs:2940:11)\n    at IncomingMessage.emit (node:events:539:35)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":15000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{"Blob":null},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) time-translate/0.8.2 Chrome/104.0.5112.124 Electron/20.3.8 Safari/537.36","Content-Length":"149","Accept-Encoding":"gzip, compress, deflate, br"},"baseURL":"https://api.niutrans.com","url":"/NiuTransServer/translation","method":"post","data":"{\"from\":\"en\",\"to\":\"zh\",\"apikey\":\"cac7d8ffe82465cb2559f0f3afb07062\",\"src_text\":\"Appalachia’s Gentrification - Clash of Locals & Outsiders 🇺🇸\"}","httpsAgent":{"_events":{},"_eventsCount":0,"timeout":null,"maxFreeSockets":1,"maxSockets":1,"maxTotalSockets":null,"sockets":{},"freeSockets":{},"requests":{},"options":{},"secureProxy":false,"proxy":{"host":"127.0.0.1","port":10809}}},"code":"ERR_BAD_REQUEST","status":400}
腾讯交互翻译反馈：
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>stgw</center>
</body>
</html>

请问是怎么回事

**Comment by ByLiangCheng** [comment]
你好，如上提示都是翻译后翻译窗口的报错信息吗？可否发送一份日志到我的邮箱：byliangcheng@sina.com

**Comment by darkelfzdy** [comment]
是的，是翻译窗口的报错信息，我已把日志发你邮箱

**Comment by ByLiangCheng** [comment]
目前排查结果预估是自己的网络问题，需要先自行检查网络或因为代理的影响
